# Generated by Django 4.0 on 2022-02-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViberNgrokUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ViberNgrokUrl', models.CharField(max_length=300)),
            ],
        ),
    ]
